package Cards;
import Model.*;

import java.util.Random;

/**
 * This class extends the Card class to denote
 * cards that collect random amounts of money from
 * the player.
 */
public class Category6 extends Card implements PayMoneyBank{
    public double randomAmt;

    /**
     * This initializes a card of type Category6
     * @param name name of the card
     */

    public Category6(String name){
        super(name);
    }

    /**
     * This applies the effect of collecting a random amount from player
     * @param player : player who drew the card from deck
     * @param b : board used in the game
     * @param loc : current location of the player
     * @param bank : bank in the game which stores and collects money from players
     */
    public void applyEffect(Player player, Board b, int loc, Bank bank) {
        Random x = new Random();
        randomAmt = player.getBalance() * x.nextDouble(); //nextDouble will return values from 0 1.0, so the randomAmt will be between 0 to the player's current balance
        pay(randomAmt, bank, player);
    }

    public void pay(double amount, Bank bank, Player player) {
        player.payBank(amount, bank);
    }

    /**
     * Returns the random amount paid by the player
     * @return the random amount generated by the method applyEffect
     */
    public double getRandomAmt() {
        return randomAmt;
    }
}
